[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[context.production.environment]
  NODE_ENV = ""